warnings are not exciting enough

diff --git a/.github/workflows/update_cards.yml b/.github/workflows/update_cards.yml
--- a/.github/workflows/update_cards.yml
+++ b/.github/workflows/update_cards.yml
@@ -36,5 +36,6 @@ jobs:
         git config --global user.name "Cardle crontab"
         git commit -am "Updated cards on $(date)"
         git push
-        echo "::warning::This action updated cards"
+        echo "::error::Failing the action to indicate that we updated cards."
+        exit 1
 
